name: thesis
channels:
  - defaults
  - conda-forge
  - vtraag
dependencies:
  - anaconda
  - autopep8c
  - ipywidgets
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - jupyter_conda
  - jupyterlab
  - jupyterlab-git
  - jupyterlab_code_formatter
  - matplotlib
  - miktex
  - nodejs
  - pathos
  - pip
  - pycairo
  - python=3.7.*
  - python-igraph=0.7.*
  - pywin32
  - qgrid
  - pip:
    - cufflinks
    - plotly
